(()=>{'use strict';
const $=id=>document.getElementById(id), STORAGE='uc6_sabor_praca_avaliacao_v1';
const tickets=[
{id:'001',title:'Nova informação no cadastro',desc:'A gerência deseja classificar os produtos como Sanduíche, Salgado ou Bebida. Adicione à estrutura existente um campo de texto de até 50 caracteres para armazenar essa categoria, sem recriar a tabela e sem perder os registros já cadastrados. Confira se a coluna foi criada e se os produtos anteriores permanecem registrados.',tips:['Qual é a diferença entre modificar uma tabela e cadastrar um registro?','Qual comando altera a estrutura sem recriar a tabela?','Como verificar se os dados anteriores foram preservados?'],sql:'ALTER TABLE nome_tabela\nADD COLUMN nome_coluna TIPO_DE_DADO;'},
{id:'002',title:'Novo produto no cardápio',desc:'Cadastre Pão de Queijo, com preço de R$ 6,00 e categoria Salgado. Depois, consulte o registro para confirmar o cadastro.',tips:['Quais atributos precisam receber valores?','A coluna adicionada no ticket anterior já está disponível?','Como consultar o registro depois da inserção?'],sql:'INSERT INTO nome_tabela (coluna1, coluna2)\nVALUES (valor1, valor2);'},
{id:'003',title:'Reajuste de preço',desc:'O Pão de Queijo passou a custar R$ 7,00. Atualize somente o registro desse produto e confira o resultado.',tips:['Você precisa cadastrar outro produto ou modificar um existente?','Como identificar apenas o registro desejado?','O que poderia acontecer se o comando não tivesse uma condição WHERE?'],sql:'UPDATE nome_tabela\nSET nome_coluna = novo_valor\nWHERE coluna_identificadora = valor;'},
{id:'004',title:'Relatório de produtos',desc:'Apresente o nome e o preço dos produtos que custam mais de R$ 10,00, do mais caro para o mais barato.',tips:['Quais colunas devem aparecer no resultado?','Qual condição identifica os registros desejados?','Qual ordenação coloca os maiores valores primeiro?'],sql:'SELECT coluna1, coluna2\nFROM nome_tabela\nWHERE coluna_filtro > valor\nORDER BY coluna_ordenacao DESC;'},
{id:'005',title:'Exclusão segura',desc:'Cadastre Produto Teste, com preço de R$ 1,00 e categoria Salgado. Esse produto não estará vinculado a pedidos. Consulte seu identificador e exclua somente esse registro. Confira que os demais produtos permanecem cadastrados.',tips:['Como localizar o identificador do registro de teste?','Como garantir que somente esse registro será excluído?','Como confirmar que os outros registros continuam cadastrados?'],sql:'SELECT * FROM nome_tabela\nWHERE coluna_identificadora = valor;\n\nDELETE FROM nome_tabela\nWHERE coluna_identificadora = valor;'}
];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
$('tickets').innerHTML=tickets.map(t=>`<article class="ticket"><div class="ticket-tag">TICKET #${t.id}</div><h3>${esc(t.title)}</h3><p>${esc(t.desc)}</p><label class="field" for="ticket-${t.id}">Seus comandos SQL</label><textarea class="sql" data-save spellcheck="false" id="ticket-${t.id}" placeholder="-- Escreva e confira seus comandos..."></textarea><details><summary>💡 Dica técnica — Como raciocinar</summary><div class="details-body"><ol>${t.tips.map(x=>`<li>${esc(x)}</li>`).join('')}</ol><p>Depois de executar, confira se o resultado corresponde à solicitação da gerência.</p></div></details><details><summary>⌨️ Consultar sintaxe SQL</summary><div class="details-body"><pre>${esc(t.sql)}</pre><p>Modelo genérico: adapte os nomes e valores à sua solução.</p></div></details></article>`).join('');
const checks=['Justifiquei as escolhas das Missões 1 e 2.','Identifiquei entidades, atributos, PKs, FKs e cardinalidades.','Expliquei a normalização e construí o modelo lógico.','Criei as tabelas com as restrições exigidas.','Cadastrei e conferi os registros fornecidos.','Executei e conferi os cinco tickets.','Anexei a imagem do modelo ou informei um link acessível.'];
$('checks').innerHTML=checks.map((x,i)=>`<label class="check"><input type="checkbox" data-save id="check-${i}">${esc(x)}</label>`).join('');
// Melhoria progressiva: o textarea original permanece como fonte de verdade para salvar e exportar.
function setupSQLEditors(){document.querySelectorAll('textarea.sql').forEach((textarea,index)=>{const container=document.createElement('div');container.className='sql-editor';const tools=document.createElement('div');tools.className='sql-tools';const caption=document.createElement('span');caption.className='small';caption.textContent='Editor SQL · Tab insere 2 espaços';const actions=document.createElement('div');actions.className='toolbar';const copy=document.createElement('button');copy.type='button';copy.className='btn';copy.textContent='Copiar SQL';copy.setAttribute('aria-label','Copiar código SQL');const expand=document.createElement('button');expand.type='button';expand.className='btn';expand.textContent='Expandir';expand.setAttribute('aria-expanded','false');const area=document.createElement('div');area.className='sql-code-area';const gutter=document.createElement('div');gutter.className='sql-line-numbers';gutter.setAttribute('aria-hidden','true');textarea.parentNode.insertBefore(container,textarea);container.appendChild(tools);tools.append(caption,actions);actions.append(copy,expand);container.appendChild(area);area.append(gutter,textarea);const updateLines=()=>{const count=Math.max(1,textarea.value.split('\n').length);gutter.textContent=Array.from({length:count},(_,i)=>String(i+1)).join('\n');gutter.scrollTop=textarea.scrollTop;};textarea.addEventListener('input',updateLines);textarea.addEventListener('scroll',()=>{gutter.scrollTop=textarea.scrollTop;});textarea.addEventListener('keydown',event=>{if(event.key!=='Tab'||event.ctrlKey||event.altKey||event.metaKey)return;event.preventDefault();const start=textarea.selectionStart,end=textarea.selectionEnd,spaces='  ';textarea.setRangeText(spaces,start,end,'end');textarea.dispatchEvent(new Event('input',{bubbles:true}));});copy.addEventListener('click',async()=>{try{if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(textarea.value);else{textarea.focus();textarea.select();if(!document.execCommand('copy'))throw Error('Cópia indisponível');}copy.textContent='Copiado!';}catch(e){copy.textContent='Selecione e copie (Ctrl+C)';textarea.focus();textarea.select();}setTimeout(()=>{copy.textContent='Copiar SQL';},1800);});expand.addEventListener('click',()=>{const expanded=container.classList.toggle('expanded');expand.textContent=expanded?'Recolher':'Expandir';expand.setAttribute('aria-expanded',String(expanded));});updateLines();});}
setupSQLEditors();
const missionGroups=[['q11','q12','q13'],['q21','q22','q23'],['q31','q32','q33','modelo','q35','q36'],['ticket-001','ticket-002','ticket-003','ticket-004','ticket-005']];
function updateMissionNavigation(){missionGroups.forEach((group,i)=>{const done=group.filter(id=>{if(id==='modelo')return Boolean(imageData||validURL($('modelo-link').value.trim()));if(['q11','q21','q23'].includes(id))return Boolean(document.querySelector('input[name="'+id+'"]:checked'));return Boolean($(id)?.value?.trim());}).length;const el=$('nav-progress-'+(i+1));if(el)el.textContent=done+'/'+group.length;});}
const missionToggle=$('mission-nav-toggle'),missionLinks=$('mission-nav-links');
function setMissionNavCollapsed(collapsed){missionLinks.hidden=collapsed;missionToggle.setAttribute('aria-expanded',String(!collapsed));missionToggle.textContent=collapsed?'▾ Mostrar navegação':'▴ Ocultar navegação';}
try{setMissionNavCollapsed(localStorage.getItem('uc6_mission_nav_collapsed')==='1');}catch(e){setMissionNavCollapsed(false);}
missionToggle.addEventListener('click',()=>{const collapsed=!missionLinks.hidden;setMissionNavCollapsed(collapsed);try{localStorage.setItem('uc6_mission_nav_collapsed',collapsed?'1':'0');}catch(e){}});
const savedFields=()=>Array.from(document.querySelectorAll('[data-save]'));
function values(){let data={};savedFields().forEach(e=>{if(e.type==='radio'){if(e.checked)data[e.name]=e.value;}else if(e.type==='checkbox')data[e.id]=e.checked;else data[e.id]=e.value;});return data;}
function restore(data){if(!data||typeof data!=='object')return;savedFields().forEach(e=>{if(e.type==='radio')e.checked=data[e.name]===e.value;else if(e.type==='checkbox')e.checked=!!data[e.id];else if(typeof data[e.id]==='string')e.value=data[e.id];if(e.matches('textarea.sql'))e.dispatchEvent(new Event('input'));});if($('modelo-link').value.trim()&&!imageData)setModelMethod('link');syncModelControls();updateProgress();}
function save(){persistStudent();updateProgress();}
const IMAGE_DB='uc6_modelo_imagem_v3', IMAGE_STORE='files';
// O rascunho e a imagem só são restaurados após confirmação da identidade do aluno.
const studentKey=()=>{const m=$('matricula').value.trim().toLowerCase(),e=$('email').value.trim().toLowerCase();return m&&e?encodeURIComponent(m+'|'+e):null;};
let activeStudent=null;
const scopedStorage=key=>STORAGE+':'+key;
function showSaveStatus(message,state='info'){$('save-status').textContent=message;$('save-status').dataset.state=state;}
function persistStudent(){const key=studentKey();if(!key){showSaveStatus('Informe matrícula e e-mail para ativar o salvamento');return;}activeStudent=key;try{localStorage.setItem(scopedStorage(key),JSON.stringify(values()));showSaveStatus('Salvo às '+new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit',second:'2-digit'}),'saved');}catch(e){showSaveStatus('Falha ao salvar: exporte uma cópia JSON','error');}}
async function switchStudent(){const key=studentKey();if(!key||key===activeStudent)return;const prior=activeStudent;activeStudent=key;let obj=null;try{obj=JSON.parse(localStorage.getItem(scopedStorage(key))||'null');}catch(e){}if(obj){restore(obj);showSaveStatus('Rascunho recuperado para esta identificação','saved');}else if(prior){savedFields().forEach(el=>{if(['nome','matricula','email','turma'].includes(el.id))return;if(el.type==='radio'||el.type==='checkbox')el.checked=false;else el.value='';});}imageData=null;imageFormat=null;imageName='';$('preview').removeAttribute('src');$('preview').style.display='none';$('img-status').textContent='Nenhuma imagem anexada.';syncModelControls();try{const record=await imageStorage('get',null,key);if(key!==activeStudent)return;if(record?.data&&/^data:image\/(png|jpeg);base64,/.test(record.data))setImage(record.data,record.format,record.name);else if($('modelo-link').value.trim())setModelMethod('link');}catch(e){}updateProgress();}
function openImageDB(){return new Promise((resolve,reject)=>{if(!window.indexedDB)return reject(Error('IndexedDB indisponível'));const r=indexedDB.open(IMAGE_DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(IMAGE_STORE))r.result.createObjectStore(IMAGE_STORE);};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function imageStorage(mode, value, key=activeStudent){if(!key)throw Error('Identifique o aluno antes de armazenar imagens');const db=await openImageDB();try{return await new Promise((resolve,reject)=>{const tx=db.transaction(IMAGE_STORE,mode==='get'?'readonly':'readwrite');const st=tx.objectStore(IMAGE_STORE);const r=mode==='get'?st.get(key):mode==='delete'?st.delete(key):st.put(value,key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}finally{db.close();}}
function validURL(s){try{const u=new URL(s);return u.protocol==='https:'&&!!u.hostname&& !/\s/.test(s);}catch{return false;}}
function missingItems(){const list=[];const required=[['nome','Nome completo'],['matricula','Matrícula'],['email','E-mail'],['q12','Questão 1.2'],['q13','Questão 1.3'],['q22','Questão 2.2'],['q31','Questão 3.1'],['q32','Questão 3.2'],['q33','Questão 3.3'],['q35','Questão 3.5 — SQL'],['q36','Questão 3.6 — SQL'],...tickets.map(t=>['ticket-'+t.id,'Ticket #'+t.id])];for(const [id,label] of required)if(!($(id).value||'').trim())list.push({id,label});for(const [name,label] of [['q11','Questão 1.1'],['q21','Questão 2.1'],['q23','Questão 2.3']])if(!document.querySelector(`input[name="${name}"]:checked`))list.push({id:name,label});if(document.querySelector('input[name="q21"]:checked')?.value==='Outro'&&!$('q21outro').value.trim())list.push({id:'q21outro',label:'Nome do outro SGBD'});if(!imageData&&!validURL($('modelo-link').value.trim()))list.push({id:'modelo',label:'Evidência do modelo lógico (imagem ou link HTTPS válido)'});return list;}
function updateProgress(){updateMissionNavigation();const missing=missingItems();const total=20+(document.querySelector('input[name="q21"]:checked')?.value==='Outro'?1:0);const n=total-missing.length;const pct=Math.max(0,Math.min(100,Math.round(n/total*100)));$('progress-label').textContent=`Itens preenchidos: ${pct}% (${n}/${total}) — não avalia correção`;$('progress-fill').style.width=pct+'%';}
let imageData=null,imageFormat=null,imageName='';
function setModelMethod(method){const isImage=method!=='link';$('modelo-imagem-panel').hidden=!isImage;$('modelo-link-panel').hidden=isImage;document.querySelectorAll('input[name="modelo-metodo"]').forEach(input=>{input.checked=input.value===(isImage?'imagem':'link');});}
document.querySelectorAll('input[name="modelo-metodo"]').forEach(input=>input.addEventListener('change',()=>{if(input.checked)setModelMethod(input.value);}));
function syncModelControls(){const hasImage=Boolean(imageData);$('remove-img').hidden=!hasImage;const link=$('modelo-link').value.trim();$('modelo-link-status').textContent=!link?'':validURL(link)?'✓ Endereço HTTPS válido. Verifique as permissões de acesso.':'Informe um endereço HTTPS válido.';}
$('modelo-link').addEventListener('input',syncModelControls);
setModelMethod('imagem');syncModelControls();

function setImage(data,format,name){imageData=data;imageFormat=format;imageName=name;setModelMethod('imagem');syncModelControls();$('preview').src=data;$('preview').style.display='block';$('img-status').textContent=`Imagem pronta: ${name}`;updateProgress();}
async function removeImage(){imageData=null;imageFormat=null;imageName='';$('modelo').value='';$('preview').removeAttribute('src');$('preview').style.display='none';$('img-status').textContent='Nenhuma imagem anexada.';syncModelControls();try{await imageStorage('delete');}catch(e){}updateProgress();}
$('modelo').addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;const valid=['image/png','image/jpeg'].includes(f.type);if(!valid||f.size>10*1024*1024){alert('Escolha PNG ou JPG com até 10 MB.');removeImage();return;}const reader=new FileReader();reader.onload=async()=>{const data=String(reader.result);const img=new Image();img.onload=async()=>{const fmt=f.type==='image/png'?'PNG':'JPEG';await switchStudent();if(!activeStudent){alert('Preencha matrícula e e-mail antes de anexar a imagem.');return;}setImage(data,fmt,f.name+` (${img.naturalWidth} × ${img.naturalHeight})`);imageName=f.name;try{await imageStorage('put',{data,format:fmt,name:f.name});$('img-status').textContent+=' · salvo neste navegador';}catch(e){$('img-status').textContent+=' · não foi possível salvar a imagem; exporte um JSON';}};img.onerror=()=>{alert('Não foi possível ler a imagem.');removeImage();};img.src=data;};reader.onerror=()=>{alert('Erro ao ler arquivo.');removeImage();};reader.readAsDataURL(f);});
$('remove-img').addEventListener('click',removeImage);$('test-link').addEventListener('click',()=>{const url=$('modelo-link').value.trim();if(!validURL(url)){alert('Informe um link HTTPS válido.');return;}window.open(url,'_blank','noopener,noreferrer');});
function exportBackup(){const blob=new Blob([JSON.stringify({version:2,exportedAt:new Date().toISOString(),answers:values(),modelImage:imageData?{data:imageData,format:imageFormat,name:imageName}:null},null,2)],{type:'application/json'});download(blob,`respostas_uc6_${slug($('matricula').value||'aluno')}.json`);showSaveStatus('Backup JSON baixado. Guarde o arquivo em local seguro.','saved');}
$('json-btn').addEventListener('click',exportBackup);
$('backup-bottom').addEventListener('click',()=>{save();exportBackup();});
$('import-btn').addEventListener('click',()=>$('import-file').click());$('import-file').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{if(f.size>22*1024*1024)throw Error('JSON muito grande');const obj=JSON.parse(await f.text());if(!obj.answers||typeof obj.answers!=='object')throw Error('Formato inválido');if(!confirm('Importar este arquivo substituirá as respostas atuais. Continuar?'))return;restore(obj.answers);activeStudent=studentKey();if(obj.modelImage?.data&&/^data:image\/(png|jpeg);base64,/.test(obj.modelImage.data)&&obj.modelImage.data.length<15*1024*1024){const img=new Image();img.src=obj.modelImage.data;await img.decode();const fmt=obj.modelImage.data.startsWith('data:image/png')?'PNG':'JPEG';setImage(obj.modelImage.data,fmt,String(obj.modelImage.name||'modelo.png'));try{await imageStorage('put',{data:imageData,format:imageFormat,name:imageName});}catch(e){}}else{await removeImage();}save();alert('Rascunho importado com sucesso.'+(imageData?' Imagem recuperada.':' Sem imagem incorporada; anexe-a novamente, se necessário.'));}catch(err){alert('Não foi possível importar o arquivo: '+err.message);}e.target.value='';});
function clearDraft(){if(!confirm('Apagar todas as respostas deste navegador? Esta ação não pode ser desfeita.'))return;savedFields().forEach(e=>{if(e.type==='radio'||e.type==='checkbox')e.checked=false;else if(e.id!=='turma')e.value='';});$('turma').value='2026.36.8 - Técnico em Desenvolvimento de Sistemas';removeImage();try{if(activeStudent)localStorage.removeItem(scopedStorage(activeStudent));}catch(e){}activeStudent=null;updateProgress();showSaveStatus('Rascunho limpo');$('validation-box').hidden=true;}
$('clear-btn').addEventListener('click',clearDraft);
$('clear-bottom').addEventListener('click',clearDraft);
savedFields().forEach(e=>{e.addEventListener('input',()=>{if(e.id==='matricula'||e.id==='email'){switchStudent().then(save);}else save();});e.addEventListener('change',save);});updateProgress();showSaveStatus('Informe matrícula e e-mail para recuperar seu rascunho');
function slug(s){return String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9_-]+/gi,'_').slice(0,45)||'aluno';}
function download(blob,name){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);}
const C={bg:[11,16,32],panel:[21,29,48],panel2:[28,39,61],line:[56,74,105],text:[237,245,255],muted:[171,188,211],accent:[114,197,255],good:[145,225,182]};
async function ensurePDFLibrary(){
 if(window.jspdf?.jsPDF)return true;
 for(const url of ['https://cdn.jsdelivr.net/npm/jspdf@2.5.2/dist/jspdf.umd.min.js','https://unpkg.com/jspdf@2.5.2/dist/jspdf.umd.min.js']){
  try{await new Promise((resolve,reject)=>{const sc=document.createElement('script');sc.src=url;sc.onload=resolve;sc.onerror=()=>reject(Error('CDN indisponível'));document.head.appendChild(sc);setTimeout(()=>{if(!window.jspdf?.jsPDF)reject(Error('Tempo esgotado'));},8000);});if(window.jspdf?.jsPDF)return true;}catch(e){console.warn('Falha ao carregar biblioteca PDF',url,e);}
 }
 return false;
}
function printReportFallback(existingWindow=null,preview=false){
 const popup=existingWindow||window.open('','_blank');
 if(!popup){$('pdf-status').textContent='Permita janelas pop-up para imprimir o relatório em PDF.';return;}
 const v=id=>esc($(id).value.trim()||'[Não respondido]');
 const radio=name=>esc(document.querySelector(`input[name="${name}"]:checked`)?.value||'[Não respondido]');
 const section=(title,items)=>`<section><h2>${esc(title)}</h2>${items.map(([q,question,answer])=>`<article><h3>${esc(q)}</h3><p class="question">${esc(question)}</p><pre>${answer}</pre></article>`).join('')}</section>`;
 const img=imageData?`<section class="model"><h2>Modelo lógico anexado</h2><img src="${imageData}" alt="Modelo lógico"></section>`:'';
 const requirements=document.querySelectorAll('.req');const reqHTML=Array.from(requirements).map(el=>`<p>${el.innerHTML}</p>`).join('');const referenceTables=Array.from(document.querySelectorAll('.table-wrap')).slice(0,3).map(el=>el.outerHTML).join('');
 const html=`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>${preview?'Pré-visualização':'Relatório'} UC6 - ${v('nome')}</title><style>*{box-sizing:border-box}html,body{margin:0;background:#0b1020;color:#eef5ff;font:14px/1.55 Arial,sans-serif;-webkit-print-color-adjust:exact;print-color-adjust:exact}body{padding:30px}h1{font-size:28px;color:#72c5ff}h2{font-size:20px;color:#72c5ff;border-bottom:1px solid #3b4d67;padding-bottom:8px}h3{font-size:15px;margin-bottom:4px}section{break-before:page}section:first-of-type{break-before:auto}article{background:#1b263d;border:1px solid #334761;border-radius:8px;padding:12px;margin:12px 0;break-inside:avoid}.question{color:#b4c7e0}pre{font:12px/1.55 Consolas,monospace;white-space:pre-wrap;overflow-wrap:anywhere;background:#101b2e;border-radius:6px;padding:12px;color:#edf5ff}a{color:#8bd5ff}.model img{display:block;max-width:100%;max-height:240mm;object-fit:contain;margin:auto}@page{size:A4;margin:14mm}@media print{body{padding:0}article{break-inside:auto}pre{break-inside:auto}}</style></head><body><h1>Relatório individual — UC6</h1><p><b>Sabor da Praça</b> · Técnico em Desenvolvimento de Sistemas</p><p><b>Estudante:</b> ${v('nome')}<br><b>Matrícula:</b> ${v('matricula')}<br><b>E-mail:</b> ${v('email')}<br><b>Turma:</b> ${v('turma')}</p><p>Gerado em ${esc(new Date().toLocaleString('pt-BR'))}. Avaliação manual pelo instrutor.</p><section><h2>Situação-problema e requisitos</h2><p>A Sabor da Praça precisa substituir suas planilhas por um banco organizado e confiável.</p>${reqHTML}<h2>Dados de referência</h2>${referenceTables}</section>
 ${section('Missão 1 — Tipo de banco (I1)',[['1.1','Qual tipo de banco recomenda?',radio('q11')],['1.2','Justifique com duas necessidades da lanchonete.',v('q12')],['1.3','Compare com cenário hipotético de cardápios variáveis.',v('q13')]])}
 ${section('Missão 2 — SGBD (I2)',[['2.1','Qual SGBD recomenda?',radio('q21')+(radio('q21')==='Outro'?' — '+v('q21outro'):'')],['2.2','Apresente duas razões técnicas.',v('q22')],['2.3','Qual é a função de um SGBD?',radio('q23')]])}
 ${section('Missão 3 — Modelagem e implementação (I3)',[['3.1','Entidades, atributos e chaves primárias.',v('q31')],['3.2','Relacionamentos, cardinalidades e chaves estrangeiras.',v('q32')],['3.3','Normalização e redução de redundâncias.',v('q33')],['3.4','Evidência do modelo lógico.',$('modelo-link').value.trim()?`<a href="${esc($('modelo-link').value.trim())}">${esc($('modelo-link').value.trim())}</a>`:'Imagem anexada, se houver.'],['3.5','SQL de criação e restrições.',v('q35')],['3.6','SQL de inserção e conferência.',v('q36')]])}
 ${img}
 ${section('Missão 4 — Tickets de manutenção (I4)',tickets.map(t=>['Ticket #'+t.id+' — '+t.title,t.desc,v('ticket-'+t.id)]))}
 <section><h2>Conferência e avaliação do instrutor</h2><p>${checks.map((x,i)=>($('check-'+i).checked?'☑ ':'☐ ')+esc(x)).join('<br>')}</p><p>I1: ☐ A ☐ PA ☐ NA<br>I2: ☐ A ☐ PA ☐ NA<br>I3: ☐ A ☐ PA ☐ NA<br>I4: ☐ A ☐ PA ☐ NA</p><h3>Observações do instrutor</h3><p>________________________________________________________________</p><p>________________________________________________________________</p></section></body></html>`;
 popup.document.open();popup.document.write(html);popup.document.close();popup.focus();
 if(preview){$('pdf-status').textContent='Pré-visualização aberta em nova aba. Confira o conteúdo e depois gere o PDF pelo site.';}else{$('pdf-status').textContent='Relatório aberto em nova aba. Use Ctrl+P → Salvar como PDF e ative “Gráficos de fundo” para preservar o tema escuro.';}
}
function acknowledgePending(missing,linkWarning){return new Promise(resolve=>{const dialog=$('pending-dialog'),list=$('pending-list'),back=$('pending-back'),confirm=$('pending-confirm');list.innerHTML=(missing.length?'<p>Itens não preenchidos ('+missing.length+'):</p><ul>'+missing.map(x=>'<li>'+esc(x.label)+'</li>').join('')+'</ul>':'')+(linkWarning?'<p>O link do modelo lógico não é um endereço HTTPS válido.</p>':'');let done=false;const finish=accepted=>{if(done)return;done=true;dialog.removeEventListener('cancel',cancel);back.removeEventListener('click',onBack);confirm.removeEventListener('click',onConfirm);if(dialog.open)dialog.close();resolve(accepted);};const cancel=e=>{e.preventDefault();finish(false);};const onBack=()=>finish(false);const onConfirm=()=>{const reserved=window.open('','_blank');finish(reserved||true);};dialog.addEventListener('cancel',cancel);back.addEventListener('click',onBack);confirm.addEventListener('click',onConfirm);if(typeof dialog.showModal==='function')dialog.showModal();else{finish(window.confirm('Há pendências no relatório. Deseja gerar o PDF mesmo incompleto?'));}});}
$('preview-btn').addEventListener('click',()=>printReportFallback(null,true));
let generating=false;
async function generatePDF(){
if(generating)return;
generating=true;
let fallbackWindow=null;
const status=$('pdf-status'),btn=$('pdf-btn'),box=$('validation-box');
box.hidden=true;btn.disabled=true;$('pdf-bottom').disabled=true;
const nome=$('nome').value.trim(),mat=$('matricula').value.trim(),email=$('email').value.trim();
const identificationErrors=[];
if(!nome)identificationErrors.push('Informe seu nome completo.');
if(!mat)identificationErrors.push('Informe sua matrícula.');
if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))identificationErrors.push('Informe um e-mail válido.');
if(identificationErrors.length){
 box.innerHTML='<strong>Identificação obrigatória:</strong><ul>'+identificationErrors.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul><p>Somente nome, matrícula e e-mail válido são exigidos para gerar o relatório.</p>';
 box.hidden=false;box.scrollIntoView({behavior:'smooth',block:'center'});
 status.textContent='Preencha sua identificação para gerar o relatório.';generating=false;btn.disabled=false;$('pdf-bottom').disabled=false;return;
}
const missing=missingItems();
const link=$('modelo-link').value.trim();
const linkWarning=link&&!validURL(link);
if(missing.length||linkWarning){
 box.innerHTML='<strong>Ciência sobre o relatório:</strong>'+
 (missing.length?'<p>Existem '+missing.length+' item(ns) ainda não preenchido(s):</p><ul>'+missing.map(x=>'<li>'+esc(x.label)+'</li>').join('')+'</ul>':'')+
 (linkWarning?'<p>O link informado para o modelo lógico não parece ser um endereço HTTPS válido. Ele será incluído como texto, sem garantia de acesso.</p>':'')+
 '<p><strong>Você pode gerar o PDF agora mesmo.</strong> Os campos vazios serão identificados como não respondidos. O relatório poderá estar incompleto e isso será considerado pelo instrutor na avaliação.</p>';
 box.hidden=false;
 const accepted=await acknowledgePending(missing,linkWarning);
 if(accepted&&accepted!==true)fallbackWindow=accepted;
 if(!accepted){status.textContent='Geração cancelada para revisão. Suas respostas foram preservadas.';generating=false;btn.disabled=false;$('pdf-bottom').disabled=false;return;}
}
// Reserva uma janela durante o clique, antes de qualquer await, inclusive se o jsPDF falhar após carregar.
if(!fallbackWindow)fallbackWindow=window.open('','_blank');if(fallbackWindow)fallbackWindow.document.write('<title>Preparando relatório</title><p>Preparando relatório...</p>');
if(!(await ensurePDFLibrary())){status.textContent='Biblioteca PDF indisponível. Abrindo versão para imprimir e salvar como PDF...';printReportFallback(fallbackWindow);generating=false;btn.disabled=false;$('pdf-bottom').disabled=false;return;}status.textContent='Preparando relatório completo...';try{
const {jsPDF}=window.jspdf;const pdf=new jsPDF({orientation:'portrait',unit:'mm',format:'a4',compress:true});const W=210,H=297,M=17,CW=W-2*M;let y=18,page=1;const setColor=(c)=>pdf.setTextColor(...c);const fill=(c)=>pdf.setFillColor(...c);const stroke=(c)=>pdf.setDrawColor(...c);
function base(){fill(C.bg);pdf.rect(0,0,W,H,'F');fill(C.panel);pdf.roundedRect(11,9,W-22,H-18,3,3,'F');stroke(C.line);pdf.setLineWidth(.2);pdf.line(M,H-19,W-M,H-19);pdf.setFont('helvetica','normal');pdf.setFontSize(8);setColor(C.muted);pdf.text('AVALIAÇÃO FINAL · UC6 · SABOR DA PRAÇA',M,H-13);pdf.text(`Página ${page}`,W-M,H-13,{align:'right'});}
function newPage(){pdf.addPage();page++;y=18;base();}
function room(h){if(y+h>H-27)newPage();}
function line(s,size=10,color=C.text,bold=false,space=3){pdf.setFont('helvetica',bold?'bold':'normal');pdf.setFontSize(size);setColor(color);const lines=pdf.splitTextToSize(String(s),CW);const lh=size*.48;for(const txt of lines){room(lh+2);pdf.text(txt,M,y);y+=lh;}y+=space;}
function title(s){room(18);fill(C.panel2);pdf.roundedRect(M-3,y-6,CW+6,13,2,2,'F');pdf.setFont('helvetica','bold');pdf.setFontSize(14);setColor(C.accent);pdf.text(s,M,y+2);y+=17;}
function heading(s){room(12);pdf.setFont('helvetica','bold');pdf.setFontSize(11.5);setColor(C.accent);pdf.text(s,M,y);y+=7;}
function blockText(txt,isCode=false){const s=String(txt||'').trim()||'[Não respondido]';const font=isCode?'courier':'helvetica';const size=isCode?8.5:9.5;const inner=CW-10;const lines=[];pdf.setFont(font,'normal');pdf.setFontSize(size);for(const raw of s.split(/\r?\n/)){const wrapped=pdf.splitTextToSize(raw||' ',inner);lines.push(...(wrapped.length?wrapped:[' ']));}const lh=isCode?4.3:4.8;let index=0;while(index<lines.length){if(y>H-43)newPage();const available=H-29-y;const max=Math.max(1,Math.floor((available-7)/lh));const chunk=lines.slice(index,index+max);const height=chunk.length*lh+7;if(height>available){newPage();continue;}fill(isCode?[10,18,31]:C.panel2);pdf.roundedRect(M-2,y-4,CW+4,height,2,2,'F');pdf.setFont(font,'normal');pdf.setFontSize(size);setColor(C.text);chunk.forEach((t,i)=>pdf.text(t,M+3,y+2+i*lh));y+=height+4;index+=chunk.length;}}
function qa(h,q,ans,code=false){heading(h);line(q,9.5,C.muted,false,3);blockText(ans,code);y+=3;}
base();line('RELATÓRIO INDIVIDUAL',11,C.accent,true,6);line('Avaliação Final — UC6',23,C.text,true,2);line('Sabor da Praça',21,C.accent,true,8);line('Criar e Manter Banco de Dados · Técnico em Desenvolvimento de Sistemas',10,C.muted,false,8);
fill(C.panel2);pdf.roundedRect(M-2,y-5,CW+4,42,3,3,'F');let identY=y;const who=[['Estudante',$('nome').value],['Matrícula',$('matricula').value],['E-mail',$('email').value],['Turma',$('turma').value],['Gerado em',new Date().toLocaleString('pt-BR')]];who.forEach(([k,v],i)=>{pdf.setFont('helvetica','bold');pdf.setFontSize(9);setColor(C.accent);pdf.text(k+':',M+2,identY+i*7);pdf.setFont('helvetica','normal');setColor(C.text);const val=String(v||'[Não informado]');const cut=pdf.splitTextToSize(val,CW-41)[0]||'';pdf.text(cut,M+34,identY+i*7);});y+=47;
line('Relatório integral: enunciados, respostas, scripts SQL e evidência do modelo lógico. A avaliação dos indicadores será feita pelo instrutor.',10,C.muted,false,9);
title('Situação-problema e requisitos');line('A Sabor da Praça é uma lanchonete que precisa substituir planilhas por um banco organizado, confiável e fácil de manter.',10);[
'R01 — Clientes: identificador único, nome e telefone; nome e telefone obrigatórios.',
'R02 — Produtos: identificador único, nome e preço; nome e preço obrigatórios; preço não negativo, validado no banco.',
'R03 — Pedidos: identificador, data, situação, cliente e produto obrigatórios. Situações: Pendente, Em preparo, Entregue, Cancelado; valores restritos no banco.',
'R04 — Relacionamentos: cliente pode ter vários pedidos; cada pedido tem um cliente. Produto pode estar em vários pedidos; cada pedido tem exatamente um produto.',
'R05 — Integridade: proibir vínculos inexistentes; não excluir clientes/produtos com pedidos associados nem excluir pedidos automaticamente.',
'R06 — Operações: inserir, consultar, atualizar, excluir de forma controlada e alterar a estrutura; categoria somente na Missão 4.'
].forEach(s=>line(s,9,C.text,false,3));
heading('Dados de referência');line('Clientes: Ana Souza (61999991111); Pedro Lima (61988882222); Júlia Martins (61977773333).',9);line('Produtos: X-Burguer (R$ 18,00); Coxinha (R$ 7,50); Suco Natural (R$ 8,00); Refrigerante (R$ 6,00); X-Salada (R$ 22,00).',9);line('Pedidos (07/10/2026): Ana / X-Burguer / Entregue; Pedro / Coxinha / Em preparo; Júlia / X-Salada / Pendente.',9);
newPage();title('MISSÃO 1 — Tipo de banco · I1');
qa('1.1 — Decisão técnica','Qual tipo de banco de dados você recomenda para a Sabor da Praça?',document.querySelector('input[name=q11]:checked')?.value);
qa('1.2 — Justificativa','Explique sua escolha considerando pelo menos duas necessidades da lanchonete.',$('q12').value);
qa('1.3 — Comparação','No cenário hipotético de cardápios personalizados com campos variáveis, qual outro tipo de banco poderia ser considerado? Justifique.',$('q13').value);
title('MISSÃO 2 — Escolha do SGBD · I2');
const sgbd=document.querySelector('input[name=q21]:checked')?.value;qa('2.1 — Decisão técnica','Qual SGBD você recomenda para a empresa?',sgbd==='Outro'?'Outro: '+$('q21outro').value:sgbd);
qa('2.2 — Justificativa','Apresente duas razões técnicas e explique como atendem à Sabor da Praça.',$('q22').value);
qa('2.3 — Função do SGBD','Qual é a principal função de um SGBD?',document.querySelector('input[name=q23]:checked')?.value);
newPage();title('MISSÃO 3 — Modelagem e implementação · I3');
qa('3.1 — Entidades e atributos','Identifique entidades, atributos e chaves primárias.',$('q31').value);
qa('3.2 — Relacionamentos','Informe entidades relacionadas, cardinalidades e localização das chaves estrangeiras.',$('q32').value);
qa('3.3 — Normalização','Explique um problema da repetição do telefone nos pedidos e como a organização em tabelas ajuda a evitá-lo.',$('q33').value);
heading('3.4 — Modelo lógico');line('Evidência: diagrama com entidades, atributos, PKs, FKs, relacionamentos e cardinalidades.',9.5,C.muted);const url=$('modelo-link').value.trim();if(url){line('Link informado:',9,C.accent,true,2);const linkPage=page,linkY=y;line(url,8.5,C.text);if(validURL(url)){try{const split=pdf.splitTextToSize(url,CW);const lh=8.5*.48;let currentPage=linkPage,currentY=linkY;for(const segment of split){if(currentY+lh+2>H-27){currentPage++;currentY=18;}pdf.setPage(currentPage);pdf.link(M,currentY-lh,CW,lh+1,{url});currentY+=lh;}pdf.setPage(page);}catch(e){console.warn('Link PDF',e);}}}else line('Link: [Não informado]',9,C.muted);
if(imageData){newPage();title('MODELO LÓGICO — IMAGEM ANEXADA');line(`Arquivo: ${imageName}`,9,C.muted);const img=new Image();img.src=imageData;await img.decode();const iw=img.naturalWidth,ih=img.naturalHeight;const maxW=CW,maxH=Math.max(30,H-29-y-4);const ratio=Math.min(maxW/iw,maxH/ih);const dw=iw*ratio,dh=ih*ratio;pdf.addImage(imageData,imageFormat,M+(CW-dw)/2,y,dw,dh,undefined,'FAST');y+=dh+7;}
newPage();title('MISSÃO 3 — Scripts SQL');
qa('3.5 — Criação e restrições','Crie o banco sabor_da_praca e as tabelas; implemente PKs, FKs, obrigatoriedade, validação de preço e situações, e integridade referencial.',$('q35').value,true);
qa('3.6 — Inserção e conferência','Cadastre os três clientes, cinco produtos e três pedidos; consulte e confira os registros e seus identificadores.',$('q36').value,true);
newPage();title('MISSÃO 4 — Manutenção do banco · I4');for(const t of tickets)qa(`Ticket #${t.id} — ${t.title}`,t.desc,$('ticket-'+t.id).value,true);
title('Conferência do estudante');checks.forEach((c,i)=>line(($('check-'+i).checked?'[X] ':'[ ] ')+c,9.3));
title('Avaliação do instrutor');line('I1 — Tipo de banco:     [ ] A     [ ] PA     [ ] NA',10);line('I2 — Escolha do SGBD:     [ ] A     [ ] PA     [ ] NA',10);line('I3 — Modelagem e implementação:     [ ] A     [ ] PA     [ ] NA',10);line('I4 — Manutenção do banco:     [ ] A     [ ] PA     [ ] NA',10);heading('Observações e feedback do instrutor');for(let i=0;i<5;i++){room(9);stroke(C.line);pdf.line(M,y+3,W-M,y+3);y+=10;}
line('Este relatório reproduz as respostas do estudante. Não comprova por si só a execução dos scripts no MySQL Workbench.',8,C.muted);
const filename=`Avaliacao_Final_UC6_${slug($('nome').value||'aluno')}_${slug($('matricula').value||'sem_matricula')}.pdf`;pdf.save(filename);if(fallbackWindow){fallbackWindow.close();fallbackWindow=null;}status.textContent='Relatório PDF gerado. Abra o arquivo e confira todas as páginas antes de entregar.';
}catch(e){console.error('Erro detalhado do PDF:',e);status.textContent='Erro na geração automática: '+e.message+'. Abrindo alternativa para salvar como PDF...';printReportFallback(fallbackWindow);}finally{generating=false;btn.disabled=false;$('pdf-bottom').disabled=false;}}
$('pdf-btn').addEventListener('click',generatePDF);$('pdf-bottom').addEventListener('click',()=>{$('pdf-btn').scrollIntoView({behavior:'smooth',block:'center'});generatePDF();});
})();
